version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/portfolio
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - portfolio-network
    volumes:
      - ./backend:/app
      - backend-data:/data/db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - portfolio-network
    environment:
      - VITE_API_BASE_URL=/api

  mongo:
    image: mongo:6.0
    container_name: portfolio-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=portfolio
    volumes:
      - mongodb_data:/data/db
    networks:
      - portfolio-network

  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./frontend/nginx-config:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  mongodb_data:
  backend-data:
