name: Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    
    - name: Run tests
      run: |
        cd backend
        python -m pytest
    
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder'
    
    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ${{ secrets.EC2_USERNAME }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Create deployment directory
        ssh -o StrictHostKeyChecking=no -i ${{ github.workspace }}/.ssh/id_rsa ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} \
          "mkdir -p ~/portfolio"
        
        # Copy files to EC2
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ${{ github.workspace }}/.ssh/id_rsa" \
          --exclude='.git' \
          --exclude='node_modules' \
          --exclude='venv' \
          --exclude='.github' \
          --exclude='.gitignore' \
          ./ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/portfolio/
        
        # Run deployment script on EC2
        ssh -o StrictHostKeyChecking=no -i ${{ github.workspace }}/.ssh/id_rsa ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} \
          "cd ~/portfolio && ./deploy.sh"
